// -*- generated by tools/gen_plugin_schemas.py — 请勿手改 -*-
/**
 * schemas.ts — 11 个工具的 parameters 扁平 DSL
 * ============================================================================
 *
 * ★ 本文件由 `src/tools/registry.py` 单源生成，对齐是**构造性**的。
 *   修改参数请改 registry.py 后重跑 `python tools/gen_plugin_schemas.py`，
 *   勿在此手抄。反向校验见 src/__tests__/params-alignment.mjs。
 *
 * 为什么必须是「扁平 DSL」而不是顶层 JSON Schema（2026-08-30 实测）：
 *   官方 `defineTool` 把 options.parameters 交给
 *   `parameterSchemaSpecToJsonSchema(spec)`，该函数把 spec 的**每个顶层键**
 *   当作参数名。若传 `{type:'object',properties:{...},required:[...]}`，
 *   实测报错：`parameters.type must be a value schema object` —— 即
 *   type/properties/required 被当成了三个参数名。故扁平 DSL 是唯一解。
 *
 * DSL 硬约束（逐条实测，违反会在插件加载时抛 JsonSchemaError）：
 *   1. object 类型必须显式声明 `additionalProperties: true | false`（布尔，
 *      **不能是 schema**）；缺失即报
 *      `parameters.X.additionalProperties must be explicitly true or false`
 *   2. 开放节点用 `type:'json'`（编译产物为 `{}`）；`{}` 空节点不合法
 *   3. `required: true` 写在**单个属性上**（per-property），不是顶层数组
 *   4. 白名单外关键字（minimum/maximum/pattern/format/$ref/anyOf/allOf）
 *      一律禁止
 */

/** 加载薪酬数据 — load_salary_data */
export const LoadSalaryDataParameters = {
  file_path: {
      type: 'string',
      required: true,
      description: 'csv/xlsx 绝对路径，Windows 下用 C:/... 正斜杠',
    },
  sheet_name: {
      type: 'string',
      description: 'xlsx 的 sheet 名，缺省第一个',
    },
  session_id: {
      type: 'string',
      description: '传入则复用并覆盖该会话的数据表；留空新建会话',
    },
} as const;

/** 确认字段映射 — confirm_mapping */
export const ConfirmMappingParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: 'load_salary_data 返回的会话 ID',
    },
  mapping: {
      type: 'object',
      required: true,
      additionalProperties: true,
      description: '原始列名 → 标准字段名，如 {\'工号\':\'emp_id\',\'基本工资(元/月)\':\'monthly_salary\'}',
    },
  source_file: {
      type: 'string',
      description: '数据来源说明（与加载时不同才需传）',
    },
} as const;

/** 生成脱敏副本 — desensitize_data */
export const DesensitizeDataParameters = {
  file_path: {
      type: 'string',
      description: '待脱敏的原始文件；省略时按 session_id 的来源文件自动回填',
    },
  session_id: {
      type: 'string',
      description: '用于自动定位来源文件',
    },
  output_path: {
      type: 'string',
      description: '输出路径；缺省在同目录生成 {原名}_desensitized.csv',
    },
  salary_jitter: {
      type: 'number',
      description: '薪资扰动幅度，0.15=±15%（默认）。越大越不可还原、统计特征失真越多',
    },
  keep_ratio: {
      type: 'boolean',
      description: '是否做总额守恒回缩使薪资总额恢复原值，默认 true（强烈建议保持）',
    },
  id_mode: {
      type: 'string',
      enum: [
      'hash',
      'seq'
    ],
      description: 'hash=加盐哈希（不可逆，默认）；seq=序号（可逆，仅内部流转）',
    },
  seed: {
      type: 'number',
      description: '随机种子；给出则可复现（演示/回归用），生产建议留空',
    },
  sheet_name: {
      type: 'string',
      description: 'xlsx 的 sheet 名',
    },
} as const;

/** 薪酬现状诊断 — analyze_current_state */
export const AnalyzeCurrentStateParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID',
    },
  red_cr: {
      type: 'number',
      description: '红圈 CR 阈值，缺省 1.20',
    },
  green_cr: {
      type: 'number',
      description: '绿圈 CR 阈值，缺省 0.80',
    },
  level_field: {
      type: 'string',
      description: '职级列名，缺省 level',
    },
  salary_field: {
      type: 'string',
      description: '月薪列名，缺省 monthly_salary',
    },
  annual_months: {
      type: 'integer',
      description: '年化月数，缺省 12',
    },
  write_back: {
      type: 'boolean',
      description: '是否把 CR/渗透率/圈层列回写会话，缺省 true',
    },
} as const;

/** 生成薪酬带宽 — generate_band */
export const GenerateBandParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID（映射须已确认）',
    },
  mode: {
      type: 'string',
      enum: [
      'optimize',
      'new'
    ],
      description: 'optimize=基于现状优化（默认）；new=全新设计（等比阶梯+成本中性拟合）',
    },
  levels: {
      type: 'array',
      items: {
          type: 'string',
        },
      description: '参与设计的职级序列；缺省用数据中出现的全部职级并自动排序',
    },
  midpoint_source: {
      type: 'string',
      enum: [
      'current_median',
      'market_p50',
      'market_custom',
      'explicit'
    ],
      description: '中位值来源：current_median=现状中位数（内部公平，默认）；market_p50=表内市场 P50（外部竞争力）；market_custom/explicit=用 midpoint_custom',
    },
  midpoint_custom: {
      type: 'object',
      additionalProperties: true,
      description: '{职级: 中位值}，market_custom / explicit 模式必填',
    },
  midpoint_diff: {
      type: 'number',
      description: '相邻职级中位值级差，如 0.15 表示每级 +15%；缺省 0.15',
    },
  spread_mode: {
      type: 'string',
      enum: [
      'tier_default',
      'uniform',
      'explicit'
    ],
      description: '带宽幅度来源：tier_default=按职级分层（基层 25%→高层 60%，默认）；uniform=全局统一用 spread_uniform；explicit=用 spread_by_level',
    },
  spread_uniform: {
      type: 'number',
      description: 'spread_mode=uniform 时的统一带宽幅度，如 0.35',
    },
  spread_by_level: {
      type: 'object',
      additionalProperties: true,
      description: 'spread_mode=explicit 时逐职级指定，如 {\'P1\':0.25,\'M3\':0.60}',
    },
  anchor_level: {
      type: 'string',
      description: 'new 模式的锚点职级；缺省最低职级',
    },
  round_to: {
      type: 'integer',
      description: '取整步长，100=取整到百元（默认）；0=不取整',
    },
  export: {
      type: 'boolean',
      description: '是否导出带宽表 CSV，缺省 true',
    },
  write_back: {
      type: 'boolean',
      description: '是否把带宽三列回写会话，缺省 true',
    },
} as const;

/** 市场对标 — market_benchmark */
export const MarketBenchmarkParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID',
    },
  strategy: {
      type: 'string',
      enum: [
      'auto',
      'P25',
      'P50',
      'P75'
    ],
      description: '全局对标分位；auto=按岗位序列默认策略（缺省）',
    },
  strategy_by_family: {
      type: 'object',
      additionalProperties: true,
      description: '岗位序列 → 分位，如 {\'销售\':\'P75\',\'职能\':\'P50\'}',
    },
  group_by: {
      type: 'array',
      items: {
          type: 'string',
        },
      description: '分组维度，取值 level / job_family / dept；缺省 [\'level\']',
    },
  make_charts: {
      type: 'boolean',
      description: '是否出市场差距图，缺省 true',
    },
} as const;

/** 调薪模拟 — simulate_increase */
export const SimulateIncreaseParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID',
    },
  budget_pct: {
      type: 'number',
      required: true,
      description: '调薪预算占调薪前年度薪资总额的比例，如 0.06 = 6%',
    },
  strategies: {
      type: 'array',
      items: {
          type: 'string',
          enum: [
        'A',
        'B',
        'C',
        'D'
      ],
        },
      description: '要模拟的策略，缺省 [\'A\',\'B\',\'C\',\'D\']',
    },
  custom_weights: {
      type: 'object',
      additionalProperties: true,
      description: '自定义绩效权重，如 {\'A\':2.0,\'B\':1.2,\'C\':0.4,\'D\':0}；缺省取 schemas.PERF_WEIGHTS',
    },
  cap_pct: {
      type: 'number',
      description: '个人单次涨幅上限，如 0.20（缺省 0.20）',
    },
  green_target: {
      type: 'string',
      description: '策略 B 的补底目标：\'band_min\'（缺省）或 CR 数值字符串如 \'0.85\'',
    },
  frozen_for_red: {
      type: 'boolean',
      description: '策略 D 下红圈是否完全冻结且不占调薪池，缺省 true',
    },
  make_charts: {
      type: 'boolean',
      description: '是否出前后对比图与成本图，缺省 true',
    },
} as const;

/** 固浮比模拟 — simulate_pay_mix */
export const SimulatePayMixParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID',
    },
  target_mix: {
      type: 'object',
      additionalProperties: true,
      description: '岗位序列 → 目标固浮比 \'固定:浮动\'，如 {\'销售\':\'40:60\'}；缺省取 schemas.JOB_FAMILY_PAY_MIX',
    },
  mix_source: {
      type: 'string',
      enum: [
      'family_default',
      'existing',
      'explicit'
    ],
      description: '固浮比来源，缺省 family_default',
    },
  achievement_range: {
      type: 'array',
      items: {
          type: 'number',
        },
      description: '业绩达成率扫描区间 [min,max,step]，缺省 [0,1.5,0.1]',
    },
  make_charts: {
      type: 'boolean',
      description: '是否出收入曲线图，缺省 true',
    },
} as const;

/** 岗位价值评估 — calc_job_score */
export const CalcJobScoreParameters = {
  session_id: {
      type: 'string',
      description: '会话 ID（批量打分或回写职级建议时需要）',
    },
  model: {
      type: 'string',
      enum: [
      'hay',
      'mercer'
    ],
      required: true,
      description: 'hay=海氏三要素；mercer=美世 IPE 四因素',
    },
  position: {
      type: 'string',
      description: '岗位名称，用于输出标题',
    },
  scores: {
      type: 'object',
      additionalProperties: true,
      description: '子维度 → 1-10 分，子维度名见 schemas.JOB_EVAL_MODELS[model]',
    },
  batch_file: {
      type: 'string',
      description: '批量打分表路径（csv/xlsx），与 scores 二选一',
    },
  template_out: {
      type: 'string',
      description: '指定则导出空白打分模板到该路径',
    },
} as const;

/** 生成诊断报告 — generate_report */
export const GenerateReportParameters = {
  session_id: {
      type: 'string',
      required: true,
      description: '会话 ID',
    },
  title: {
      type: 'string',
      description: '报告标题，缺省「薪酬诊断报告」',
    },
  include_sections: {
      type: 'array',
      items: {
          type: 'string',
        },
      description: '只生成指定章节（中文标题/子串或 \'1\'-\'7\' 序号）；缺省全部 7 章',
    },
  formats: {
      type: 'array',
      items: {
          type: 'string',
          enum: [
        'md',
        'html'
      ],
        },
      description: '输出格式，缺省 [\'md\',\'html\']',
    },
} as const;

/** 运行薪酬分析代码 — run_comp_code */
export const RunCompCodeParameters = {
  code: {
      type: 'string',
      required: true,
      description: 'Python 代码（同步，不支持 async）',
    },
  description: {
      type: 'string',
      required: true,
      description: '一句话说明这段代码做什么',
    },
  session_id: {
      type: 'string',
      description: '会话 ID，沙箱内通过 comp/tools 访问该会话',
    },
  timeout_s: {
      type: 'number',
      description: '超时秒数，缺省 15，上限 60',
    },
} as const;

/** 11 个工具的元数据（name 为唯一键） */
export interface ToolMeta {
  name: string;
  title: string;
  description: string;
  parameters: Record<string, unknown>;
  timeoutMs: number;
  isConcurrencySafe: () => boolean;
}

export const TOOL_METAS: ToolMeta[] = [
  {
    name: 'load_salary_data',
    title: '加载薪酬数据',
    description: '读取薪酬表（csv/xlsx），自动清洗脏数据（重复行、非数字薪资、绩效等级大小写）并给出字段映射建议。必须在其他分析工具之前调用。只返回前 5 行预览与统计摘要，绝不返回全量明细。',
    parameters: LoadSalaryDataParameters as unknown as Record<string, unknown>,
    timeoutMs: 60000,
    isConcurrencySafe: () => false,
  },
  {
    name: 'confirm_mapping',
    title: '确认字段映射',
    description: '确认或修正字段映射，把原始列名标准化为内部 18 个标准字段。映射固化后全部下游分析工具才可用。mapping 的键是原始列名、值是标准字段名。',
    parameters: ConfirmMappingParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => false,
  },
  {
    name: 'desensitize_data',
    title: '生成脱敏副本',
    description: '对薪酬文件生成脱敏副本用于外发/演示：姓名→姓+**、员工 ID→加盐哈希、薪资乘随机扰动并做总额守恒回缩、司龄分箱、删除身份证/手机号等直接标识列。只写出新文件，不改动会话内的原数据。',
    parameters: DesensitizeDataParameters as unknown as Record<string, unknown>,
    timeoutMs: 60000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'analyze_current_state',
    title: '薪酬现状诊断',
    description: '薪酬现状诊断：为每位员工计算 CR（月薪/带宽中位值）与带宽渗透率，判定红圈（超上限/CR 过高）、绿圈（低于下限/CR 过低），并测算年化成本溢出与补足金额。前置：必须已 generate_band。',
    parameters: AnalyzeCurrentStateParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'generate_band',
    title: '生成薪酬带宽',
    description: '生成薪酬带宽表并诊断相邻职级重叠度。下限=中位值/(1+带宽幅度/2)，上限=下限×(1+带宽幅度)；带宽幅度采用相对下限口径 (上限−下限)/下限。mode=optimize 基于现状中位数优化（默认）；mode=new 按锚点+级差全新设计并做成本中性拟合。',
    parameters: GenerateBandParameters as unknown as Record<string, unknown>,
    timeoutMs: 60000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'market_benchmark',
    title: '市场对标',
    description: '把公司各职级/岗位序列薪资与市场分位值（P25/P50/P75）对标，按薪酬策略计算差距率、市场对标指数与追平目标分位的年化成本。策略 auto 按岗位序列取（销售/技术 P75、管理/职能 P50、操作 P25）。',
    parameters: MarketBenchmarkParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'simulate_increase',
    title: '调薪模拟',
    description: '在给定调薪总预算下模拟 4 种分配策略并对比：A=平均分配、B=优先补绿圈、C=按绩效加权、D=优先保留（红圈冻结）。输出各策略成本、涨幅分布、调薪前后红绿圈人数与 CR 变化，并给出推荐策略与理由。预算守恒：各策略总成本严格等于预算额。',
    parameters: SimulateIncreaseParameters as unknown as Record<string, unknown>,
    timeoutMs: 120000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'simulate_pay_mix',
    title: '固浮比模拟',
    description: '按岗位序列模拟固定/浮动薪酬结构：固定部分=年度总现金×固定占比，浮动目标=年度总现金×浮动占比，实际总收入=固定部分+浮动目标×业绩达成率。输出各序列现状与目标固浮比、收入-达成率曲线、下行风险与上行空间。',
    parameters: SimulatePayMixParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'calc_job_score',
    title: '岗位价值评估',
    description: '用海氏三要素法（hay）或美世 IPE 四因素法（mercer）给岗位打分，输出各要素加权得分、岗位分值（job_score = round(原始分×160)）与建议职级。子维度按 1-10 分打分；缺失维度按同要素均值兜底并记警告。注意：本项目为简易打分表，非正式认证评估。',
    parameters: CalcJobScoreParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => true,
  },
  {
    name: 'generate_report',
    title: '生成诊断报告',
    description: '汇总全部上游分析结果，生成七章结构的薪酬诊断报告（执行摘要/数据概览/现状诊断/带宽与市场/调薪模拟/固浮比/落地路线图），输出 Markdown 与内嵌图表的 HTML。缺数据的章节会降级为提示文案而不中断。',
    parameters: GenerateReportParameters as unknown as Record<string, unknown>,
    timeoutMs: 120000,
    isConcurrencySafe: () => false,
  },
  {
    name: 'run_comp_code',
    title: '运行薪酬分析代码',
    description: '在受限 Python 沙箱中执行一段分析代码，用于批量编排薪酬工具、或直接用 pandas 做自定义分析。可用：pandas as pd、numpy as np、math、statistics、json；已注入 tools 对象（其余 10 个薪酬工具的同步封装）与 comp 会话对象（comp.df() 取只读数据副本）。禁止：文件读写、网络、子进程、导入白名单外模块、访问 __class__/__globals__ 等双下划线属性。每次运行全新环境，只有 print() 的内容与赋值给 result 的对象会返回。超时 15 秒。',
    parameters: RunCompCodeParameters as unknown as Record<string, unknown>,
    timeoutMs: 30000,
    isConcurrencySafe: () => false,
  },
];
