# -*- coding: utf-8 -*-
"""从 src/tools/registry.py 生成 src/plugins/comp-tool/src/schemas.ts。

为什么用生成而不是手抄：
  TS 侧的 parameters DSL 必须与 Python registry 逐字段对齐。手抄必错；
  由 registry 单源生成则对齐是**构造性**的，后续只需重跑本脚本。
  生成后再由 src/plugins/comp-tool/src/__tests__/params-alignment.mjs 反向
  比对一遍（双向兜底：正向生成保证同源，反向比对证明没漂）。

用法（仓库根目录执行）：
    python tools/gen_plugin_schemas.py

DSL 修正规则（全部经 2026-08-30 实测 dsh-tools defineTool 确认）：
  1. additionalProperties 若是 dict（schema 形态）→ 改 true。
     实测报错：'parameters.X.additionalProperties must be explicitly true or false'
  2. 剥掉白名单外关键字（minimum/maximum/pattern/format/$ref/anyOf/allOf 等）
  3. object 类型必须带布尔 additionalProperties

★ 历史缺陷（2026-08-30 修复，勿复发）：
  emit() 渲染「嵌套 dict 属性」时漏了尾部逗号，导致
      levels: { type:'array', items:{ type:'string' } description:'...' }
  这种非法 TS（6 处参数，全部是「有 items 且后面跟 description」）。
  根因：顶层属性的逗号由 main() 补，嵌套属性无人补。
  修复：逗号统一由 emit() 自己补，main() 不再越权拼接。
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)

from src.tools import registry  # noqa: E402

# dsh-tools value-schema DSL 白名单（实测）
KEEP = {"type", "description", "required", "enum", "default", "title",
        "properties", "additionalProperties", "items", "oneOf", "const"}


def fix(node, path=""):
    """递归规整一个参数节点为合法的 dsh 扁平 DSL。"""
    if not isinstance(node, dict):
        return node
    out = {}
    for k, v in node.items():
        if k not in KEEP:
            continue
        if k == "additionalProperties":
            # ★ 实测：必须是布尔，不能是 schema
            out[k] = True if isinstance(v, dict) else bool(v)
        elif k == "properties" and isinstance(v, dict):
            out[k] = {pk: fix(pv, path + "." + pk) for pk, pv in v.items()}
        elif k == "items" and isinstance(v, dict):
            out[k] = fix(v, path + ".items")
        elif k == "oneOf" and isinstance(v, list):
            out[k] = [fix(x, path + ".oneOf") for x in v]
        else:
            out[k] = v
    # ★ 实测：object 类型缺 additionalProperties 直接报错
    if out.get("type") == "object" and "additionalProperties" not in out:
        out["additionalProperties"] = True
    return out


def ts_str(s):
    """生成 TS 单引号字符串字面量（转义反斜杠/单引号/换行）。"""
    if s is None:
        return "''"
    s = str(s).replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return "'" + s + "'"


def emit(node, indent):
    """把 dict 渲染成 TS 对象字面量。

    ★ 每条属性（含嵌套 dict）都必须自带尾逗号 —— 这是 2026-08-30
      `items:{...}` 后漏逗号导致 6 处语法错误的修复点。
      返回的是**不含**外层尾逗号的行列表，由调用方决定是否补。
    """
    pad = " " * indent
    lines = ["{"]
    for k, v in node.items():
        key = k if k.isidentifier() else ts_str(k)
        if isinstance(v, dict):
            body = "\n".join(
                (pad + "  " if i else "") + ln
                for i, ln in enumerate(emit(v, indent + 2)))
            lines.append(f"{pad}  {key}: {body},")
        elif isinstance(v, list):
            inner = ",\n".join(
                "\n".join((pad + "    " if j else "") + ln
                          for j, ln in enumerate(emit(x, indent + 4)))
                if isinstance(x, dict) else pad + "    " + ts_str(x)
                for x in v)
            lines.append(f"{pad}  {key}: [\n{inner}\n{pad}  ],")
        elif isinstance(v, bool):
            lines.append(f"{pad}  {key}: {'true' if v else 'false'},")
        elif isinstance(v, (int, float)):
            lines.append(f"{pad}  {key}: {v},")
        else:
            lines.append(f"{pad}  {key}: {ts_str(v)},")
    lines.append(pad + "}")
    return lines


def main():
    tools = registry.list_tools()
    buf = io.StringIO()
    w = buf.write

    w("""// -*- generated by tools/gen_plugin_schemas.py — 请勿手改 -*-
/**
 * schemas.ts — 11 个工具的 parameters 扁平 DSL
 * ============================================================================
 *
 * ★ 本文件由 `src/tools/registry.py` 单源生成，对齐是**构造性**的。
 *   修改参数请改 registry.py 后重跑 `python tools/gen_plugin_schemas.py`，
 *   勿在此手抄。反向校验见 src/__tests__/params-alignment.mjs。
 *
 * 为什么必须是「扁平 DSL」而不是顶层 JSON Schema（2026-08-30 实测）：
 *   官方 `defineTool` 把 options.parameters 交给
 *   `parameterSchemaSpecToJsonSchema(spec)`，该函数把 spec 的**每个顶层键**
 *   当作参数名。若传 `{type:'object',properties:{...},required:[...]}`，
 *   实测报错：`parameters.type must be a value schema object` —— 即
 *   type/properties/required 被当成了三个参数名。故扁平 DSL 是唯一解。
 *
 * DSL 硬约束（逐条实测，违反会在插件加载时抛 JsonSchemaError）：
 *   1. object 类型必须显式声明 `additionalProperties: true | false`（布尔，
 *      **不能是 schema**）；缺失即报
 *      `parameters.X.additionalProperties must be explicitly true or false`
 *   2. 开放节点用 `type:'json'`（编译产物为 `{}`）；`{}` 空节点不合法
 *   3. `required: true` 写在**单个属性上**（per-property），不是顶层数组
 *   4. 白名单外关键字（minimum/maximum/pattern/format/$ref/anyOf/allOf）
 *      一律禁止
 */
""")

    for t in tools:
        name = t["name"]
        params = t.get("parameters") or {}
        fixed = {k: fix(v, name + "." + k) for k, v in params.items()}
        var = "".join(p.capitalize() for p in name.split("_"))
        w(f"\n/** {t.get('title', name)} — {name} */\n")
        w(f"export const {var}Parameters = {{\n")
        for k, v in fixed.items():
            key = k if k.isidentifier() else ts_str(k)
            body = "\n".join(("  " if i else "") + ln
                             for i, ln in enumerate(emit(v, 2)))
            w(f"  {key}: {body},\n")
        w("} as const;\n")

    # 工具名 -> 参数表 / 时限 / 并发安全 / 标题
    w("\n/** 11 个工具的元数据（name 为唯一键） */\n")
    w("export interface ToolMeta {\n"
      "  name: string;\n"
      "  title: string;\n"
      "  description: string;\n"
      "  parameters: Record<string, unknown>;\n"
      "  timeoutMs: number;\n"
      "  isConcurrencySafe: () => boolean;\n"
      "}\n\nexport const TOOL_METAS: ToolMeta[] = [\n")
    for t in tools:
        name = t["name"]
        var = "".join(p.capitalize() for p in name.split("_"))
        safe = "true" if t.get("concurrency_safe") else "false"
        desc = ts_str(t.get("description") or "")
        title = ts_str(t.get("title") or name)
        w(f"  {{\n"
          f"    name: '{name}',\n"
          f"    title: {title},\n"
          f"    description: {desc},\n"
          f"    parameters: {var}Parameters as unknown as Record<string, unknown>,\n"
          f"    timeoutMs: {int(t.get('timeout_s') or 30) * 1000},\n"
          f"    isConcurrencySafe: () => {safe},\n"
          f"  }},\n")
    w("];\n")

    out_dir = os.path.join(ROOT, "src", "plugins", "comp-tool", "src")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "schemas.ts")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(buf.getvalue())
    print("生成:", path)
    print("工具数:", len(tools))
    print("参数合计:", sum(len((t.get('parameters') or {})) for t in tools))


if __name__ == "__main__":
    main()
